sudo: required
services:
  - docker

before_install:
  - docker build -t chengadev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chengadev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-311582721635"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
